apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-init-webhook-deployment
  labels:
    app: secrets-init-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets-init-webhook
  template:
    metadata:
      labels:
        app: secrets-init-webhook
    spec:
      containers:
        - name: secrets-init-webhook
          image: doitintl/kube-secrets-init
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          args:
            - --log-level=debug
            - server
            - --tls-cert-file=/etc/webhook/certs/cert.pem
            - --tls-private-key-file=/etc/webhook/certs/key.pem
            - --pull-policy=Always
            # uncomment for Google Cloud Secrets Manager
            # - --provider=google
            # (optional: default parameter) uncomment for AWS Secrets Manager and SSM Parameter Store
            # - --provider=aws
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      serviceAccountName: secrets-init-webhook-sa
      volumes:
        - name: webhook-certs
          secret:
            secretName: secrets-init-webhook-certs
