apiVersion: v1
kind: Service
metadata:
  name: {{ include "secrets-init.fullname" . }}
  labels:
    {{- include "secrets-init.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: webhook
  selector:
    {{- include "secrets-init.selectorLabels" . | nindent 4 }}
